version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      VUE_APP_BACKEND_URL: http://backend:3000
    volumes:
      - ./frontend:/app
    ports:
      - '8080:8080'
    depends_on:
      - backend

volumes:
  postgres_data: